services:
  postgres:
    image: postgres:16.0
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: tf123
      POSTGRES_PASSWORD: Admin!123
      POSTGRES_DB: ts_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  redis:
#    image: redis:latest
#    container_name: redis-server
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#    restart: unless-stopped
#    command: [ "redis-server", "--appendonly", "yes" ]

#  zookeeper:
#    image: ubuntu/zookeeper:latest
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#    networks:
#      - kafka_network
#    restart: always
#
#  kafka:
#    image: ubuntu/kafka:latest
#    container_name: kafka
#    ports:
#      - "9092:9092"
#    depends_on:
#      - zookeeper
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    networks:
#      - kafka_network
#    restart: always
#
#networks:
#  kafka_network:
#    driver: bridge

volumes:
  postgres_data:
    driver: local
#  redis_data:
#    driver: local