spring:
  application:
    name: taskflow
  session:
    store-type: none
  datasource:
    url: jdbc:postgresql://localhost:5432/ts_dev?currentSchema=todo
    username: tf123
    password: Admin!123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

